#!/usr/bin/env bash
# =============================================================================
# bootstrap.sh — one-shot setup after cloning whitelionred/evo-crm-community
# =============================================================================
# Usage:
#   bash scripts/bootstrap.sh
#
# What it does (idempotent):
#   1. Verifies prerequisites (docker, docker compose, git).
#   2. Initializes submodules if needed.
#   3. Registers evolution-api's docker-compose.override.yaml in the submodule's
#      local exclude list (so it stays untracked without modifying upstream
#      .gitignore).
#   4. Creates evolution-api/docker-compose.override.yaml if it doesn't exist.
#   5. Copies .env.example to .env if .env is missing, applying BACKEND_URL
#      and any other fixes documented in CUSTOMIZATIONS.md.
#   6. Copies evolution-api/env.example to evolution-api/.env if missing,
#      applying database / redis / port fixes documented in CUSTOMIZATIONS.md.
#   7. Builds images and starts the stack.
#
# If you ran setup.sh or make setup before, this script is what should have
# run instead. It is safe to re-run — every step checks for prior state.
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

green() { printf "\033[32m%s\033[0m\n" "$*"; }
cyan()  { printf "\033[36m%s\033[0m\n" "$*"; }
red()   { printf "\033[31m%s\033[0m\n" "$*" >&2; }

cyan "[1/7] Checking prerequisites..."
command -v docker >/dev/null || { red "docker not found"; exit 1; }
docker compose version >/dev/null || { red "docker compose v2 required"; exit 1; }
command -v git >/dev/null || { red "git not found"; exit 1; }
green "  ok"

cyan "[2/7] Initializing submodules..."
git submodule update --init --recursive
green "  ok"

cyan "[3/7] Registering evolution-api override as local-excluded..."
EXCLUDE_FILE=".git/modules/evolution-api/info/exclude"
if [ -f "$EXCLUDE_FILE" ] && ! grep -qxF "docker-compose.override.yaml" "$EXCLUDE_FILE"; then
  echo "docker-compose.override.yaml" >> "$EXCLUDE_FILE"
  green "  added to $EXCLUDE_FILE"
else
  green "  already excluded or submodule not init'd (step 2 handles it)"
fi

cyan "[4/7] Creating evolution-api/docker-compose.override.yaml if missing..."
OVERRIDE_EVO="evolution-api/docker-compose.override.yaml"
if [ ! -f "$OVERRIDE_EVO" ]; then
  cat > "$OVERRIDE_EVO" <<'YAML'
# Auto-generated by scripts/bootstrap.sh — see CUSTOMIZATIONS.md
services:
  api:
    ports: !override
      - "127.0.0.1:58081:8080"
  frontend:
    ports: !override
      - "53000:80"
YAML
  green "  created $OVERRIDE_EVO"
else
  green "  $OVERRIDE_EVO already exists, skipping"
fi

cyan "[5/7] Bootstrapping monorepo .env..."
if [ ! -f .env ]; then
  cp .env.example .env
  # Fix BACKEND_URL so webhook from evolution-api container can reach evo-crm
  sed -i.bak 's|^BACKEND_URL=http://localhost:3000|BACKEND_URL=http://host.docker.internal:3000|' .env && rm -f .env.bak
  green "  created .env (BACKEND_URL patched to host.docker.internal)"
else
  green "  .env already exists, skipping (verify BACKEND_URL manually per CUSTOMIZATIONS.md)"
fi

cyan "[6/7] Bootstrapping evolution-api/.env..."
EVO_ENV="evolution-api/.env"
if [ ! -f "$EVO_ENV" ]; then
  cp evolution-api/env.example "$EVO_ENV"
  # Patch the database connection URI to the internal docker hostname
  sed -i.bak 's|^DATABASE_CONNECTION_URI=.*|DATABASE_CONNECTION_URI=postgresql://evolution:evolution_dev_password@evolution-postgres:5432/evolution_api?schema=public|' "$EVO_ENV" && rm -f "$EVO_ENV.bak"
  # Patch Redis URI
  sed -i.bak 's|^CACHE_REDIS_URI=.*|CACHE_REDIS_URI=redis://evolution-redis:6379|' "$EVO_ENV" && rm -f "$EVO_ENV.bak"
  # Ensure DB credentials referenced by the compose file exist
  {
    echo ""
    echo "# --- Added by scripts/bootstrap.sh (required by docker-compose) ---"
    echo "POSTGRES_DATABASE=evolution_api"
    echo "POSTGRES_USERNAME=evolution"
    echo "POSTGRES_PASSWORD=evolution_dev_password"
  } >> "$EVO_ENV"
  # Rotate the API key
  NEW_KEY="$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  sed -i.bak "s|^AUTHENTICATION_API_KEY=.*|AUTHENTICATION_API_KEY=${NEW_KEY}|" "$EVO_ENV" && rm -f "$EVO_ENV.bak"
  green "  created $EVO_ENV (DB URI, Redis URI, POSTGRES_* vars, API key rotated)"
  green "  >>> Evolution API key: ${NEW_KEY}"
else
  green "  $EVO_ENV already exists, skipping"
fi

cyan "[7/7] Done. Next steps (run manually):"
cat <<EOF

  docker compose build
  docker compose up -d postgres redis mailhog
  # wait for health (~30s)
  docker compose run --rm evo-auth sh -c "bundle exec rails db:prepare && bundle exec rails db:seed"
  docker compose run --rm evo-crm  sh -c "bundle exec rails db:prepare && bundle exec rails db:seed"
  docker compose up -d
  # ... then create account at http://localhost:3001/setup

  For evolution-api:
  cd evolution-api && docker compose up -d

  After creating a WhatsApp Evolution channel, run:
  bash scripts/fix-channel-state.sh <channel_id>

EOF
